name: docsify-cli

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  sidebar:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install docsify-cli
        run: |
          npm i docsify-cli -g
      #   TODO: support use of `npm ci`
      - name: Build sidebar
        env:
          DOCSIFY_BASEPATH: 'docs/'
          DOCSIFY_SIDEBAR_FILENAME: '_sidebar.md'
        run: |
          if [ -e "${DOCSIFY_BASEPATH}${DOCSIFY_SIDEBAR_FILENAME}" ]; then
            rm -rf ${DOCSIFY_BASEPATH}${DOCSIFY_SIDEBAR_FILENAME}
          fi
          docsify generate ${DOCSIFY_BASEPATH} --sidebar ${DOCSIFY_SIDEBAR_FILENAME}
          git status
          cat ${DOCSIFY_BASEPATH}${DOCSIFY_SIDEBAR_FILENAME}
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Build sidebar with docsify-cli
